Repository eskarpnes/PySSMic, pull requests merged in 2018-10, with the labels that each got.

#42 pandas in load profiles
  requirements.txt
  src/input_utils.py
  src/job.py
  src/load_profile.py
  src/message_utils.py
  tests/consumer_pytest.py
  tests/input_utils_pytest.py
  tests/job_pytest.py
Labels: in progress

#44 Feat simulator
  requirements.txt
  src/manager.py
  src/simulator.py
Labels: in progress

#45 Feat/frontend setup
  requirements.txt
  src/frontend/app.py
  src/frontend/apps/create_esn.py
  src/frontend/apps/create_sim.py
  src/frontend/apps/ex.xml
  src/frontend/apps/main.py
  src/frontend/index.py
Labels: in progress

#50 Feat simulator backend intergration
  definitions.py
  input/test/consumer_event.csv
  input/test/loads/105.csv
  input/test/loads/57_back_10.csv
  input/test/loads/57_back_11.csv
  input/test/loads/57_back_3.csv
  input/test/loads/57_back_4.csv
  input/test/loads/57_back_5.csv
  input/test/loads/57_back_6.csv
  input/test/loads/57_back_7.csv
  input/test/loads/57_back_8.csv
  input/test/loads/57_back_9.csv
  input/test/loads/91.csv
  input/test/loads/92.csv
  input/test/loads/93.csv
  input/test/loads/96.csv
  input/test/loads/97.csv
  input/test/loads/98.csv
  input/test/loads/99.csv
  input/test/predictions/57_220_1.csv
  input/test/predictions/57_220_2.csv
  input/test/predictions/57_220_3.csv
  input/test/predictions/57_220_4.csv
  input/test/predictions/59_226_1.csv
  input/test/predictions/59_226_2.csv
  input/test/predictions/59_226_3.csv
  input/test/predictions/59_226_4.csv
  input/test/predictions/60_230_1.csv
  input/test/predictions/60_230_2.csv
  input/test/predictions/60_230_3.csv
  input/test/predictions/60_230_4.csv
  input/test/producer_event.csv
  src/backend/consumer.py
  src/backend/job.py
  src/backend/manager.py
  src/simulator.py
  src/util/input_utils.py
  tests/test_input_utils_pytest.py
Labels: in progress

#52 add optimizer behavior
  src/backend/job.py
  src/backend/optimizer.py
  src/backend/producer.py
  src/load_profile_utils.py
  tests/test_job_pytest.py
  tests/test_optimizer_pytest.py
Labels: ESN 2, in progress

#51 Feat/upload xml
  src/frontend/apps/create_esn.py
  src/frontend/apps/create_sim.py
  src/frontend/apps/ex.xml
  src/frontend/apps/main.py
  src/frontend/apps/neighborhood.xml
  src/frontend/apps/test.py
  src/frontend/index.py
Labels: in progress

#68 Feat base layout
  apps/base.py
  apps/create_esn.py
  apps/create_sim.py
  apps/main.py
  index.py
  util/frontend/assets/base.css
Labels: in progress

#70 Feat upload xml
  apps/create_esn.py
  apps/main.py
  assets/popup.css
  index.py
  requirements.txt
Labels: in progress

#75 integrate optimizer with simulator
  backend/manager.py
  backend/optimizer.py
  backend/producer.py
  simulator.py
  tests/test_consumer_pytest.py
  tests/test_manager_pytest.py
  tests/test_optimizer_pytest.py
  util/input_utils.py
Labels: in progress

#79 Feat backend ids
  backend/consumer.py
  backend/job.py
  backend/manager.py
  backend/producer.py
  simulator.py
  tests/mock_clock.py
  tests/test_consumer_pytest.py
  tests/test_input_utils_pytest.py
  tests/test_job_pytest.py
  tests/test_manager_pytest.py
  tests/test_optimizer_pytest.py
  util/input_utils.py
Labels: in progress

#82 New predictions are now added to old ones
  backend/producer.py
Labels: in progress

#80 add scheduled time field
  backend/consumer.py
  backend/job.py
  backend/manager.py
  backend/optimizer.py
  backend/producer.py
Labels: in progress

#83 fix optimization
  backend/optimizer.py
  backend/producer.py
  tests/test_optimizer_pytest.py
Labels: ESN 2, bug, in progress

#88 fix diffrentiation
  backend/optimizer.py
  tests/test_optimizer_pytest.py
Labels: in progress

#90 Feat rename
  apps/simulate_esn.py
Labels: in progress

#89 Feat classes for frontend
  apps/create_esn.py
  backend/consumer_event.py
  backend/device.py
  backend/house.py
  backend/load.py
  backend/neighbourhood.py
  backend/prediction.py
  backend/producer_event.py
  backend/user.py
  index.py
  util/csv_utils.py
Labels: in progress

#92 Priority queue and simple producer scoring system implemented
  .gitignore
  backend/consumer.py
  backend/manager.py
  simulator.py
Labels: in progress

#93 Feat process data
  apps/base.py
  apps/create_esn.py
  apps/create_sim.py
  apps/simulate_esn.py
  data_processing.py
  index.py
Labels: in progress

#98 Feat threaded simulator
  simulator.py
  threaded_simulator.py
Labels: in progress

#104 algorithm options
  backend/manager.py
  backend/optimizer.py
  backend/producer.py
  simulator.py
  tests/test_manager_pytest.py
  tests/test_optimizer_pytest.py
  tests/test_optimizer_utils_pytest.py
  tests/test_producer_pytest.py
  util/optimizer_utils.py
Labels: in progress

#105 Windows multiprocessing now works, callbacks are now returns
  apps/create_sim.py
  simulator.py
  threaded_simulator.py
Labels: in progress
